# Generated by Django 2.0.5 on 2018-05-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=None, null=True)),
                ('place_embark', models.CharField(default=None, max_length=64, null=True)),
                ('date_end', models.DateField(default=None, null=True)),
                ('place_disembark', models.CharField(default=None, max_length=64, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=None, null=True)),
                ('slaves_embarked', models.PositiveIntegerField(default=None, null=True)),
                ('slaves_disembarked', models.PositiveIntegerField(default=None, null=True)),
                ('ratio_men', models.FloatField(default=None, null=True)),
                ('ratio_women', models.FloatField(default=None, null=True)),
                ('ratio_children', models.FloatField(default=None, null=True)),
                ('death_ratio', models.FloatField(default=None, null=True)),
                ('death_ratio_confirmed', models.NullBooleanField(default=None)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VI_Slaves.Nation')),
                ('region_disembark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_disembark', to='VI_Slaves.Region')),
                ('region_embark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_embark', to='VI_Slaves.Region')),
            ],
        ),
    ]
