# Generated by Django 2.0.5 on 2018-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VI_Slaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
