# Generated by Django 2.0.5 on 2018-06-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VI_Slaves', '0002_auto_20180601_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='death_ratio',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='nation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='VI_Slaves.Nation'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='place_disembark',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='place_embark',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='ratio_children',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='ratio_men',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='ratio_women',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='region_disembark',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_disembark', to='VI_Slaves.Region'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='region_embark',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_embark', to='VI_Slaves.Region'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='slaves_disembarked',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='slaves_embarked',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
