# Generated by Django 2.0.5 on 2018-06-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VI_Slaves', '0003_auto_20180601_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
