# Generated by Django 2.0.5 on 2018-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VI_Slaves', '0004_auto_20180601_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='place_disembark',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='place_embark',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
